/**
 * confluenceService.ts
 *
 * Confluence API integration for the NOC Investigation Memory System.
 * Saves completed investigations as child pages under the "NOC Investigations" parent page.
 * Searches past investigations using CQL.
 *
 * Auth: Same Atlassian Basic auth as Jira (email/token:apiToken).
 * Dev proxy: /confluence-proxy → https://{jiraSubdomain}
 */
import type { AiSettings } from '../store/aiSettings';
import type { DiagnosisResult } from '../types/diagnosis';
import type { ZendeskTicket } from './zendeskService';

export interface SavedInvestigation {
  pageId: string;
  title: string;
  url: string;
}

export interface ConfluenceSearchResult {
  pageId: string;
  title: string;
  excerpt: string;
  url: string;
  lastModified: string;
}

function confluenceBase(settings: AiSettings): string {
  if (import.meta.env.DEV) return '/confluence-proxy';
  return `https://${settings.jiraSubdomain}`;
}

function confluenceHeaders(settings: AiSettings): Record<string, string> {
  const credentials = btoa(`${settings.jiraEmail}/token:${settings.jiraToken}`);
  return {
    'Content-Type': 'application/json',
    Authorization: `Basic ${credentials}`,
  };
}

function hasConfluenceCredentials(settings: AiSettings): boolean {
  return !!(settings.jiraSubdomain && settings.jiraEmail && settings.jiraToken
    && settings.confluenceSpaceId && settings.confluenceParentPageId);
}

/**
 * Build the investigation page body in Atlassian Storage Format (XHTML).
 */
function buildInvestigationPageBody(
  ticket: ZendeskTicket | null,
  diagnosis: DiagnosisResult,
  internalNote: string,
  customerTimezone: string,
  investigator: string,
): string {
  const now = new Date().toISOString();
  const rootCauseTags = extractRootCauseTags(diagnosis.rootCause);

  const correlatedEvidence = diagnosis.correlatedLogs
    .slice(0, 15)
    .map(l => `<li><strong>[${l.rawTimestamp}] ${l.level} ${l.component}:</strong> ${escapeHtml(l.message.slice(0, 200))}<br/><em>${escapeHtml(l.reason)}</em></li>`)
    .join('\n');

  const logSources = [...new Set(diagnosis.correlatedLogs.map(l => l.component))].join(', ') || 'N/A';

  return `
<ac:structured-macro ac:name="info"><ac:rich-text-body>
<p>Auto-generated by NocLense on ${now}. Investigator: ${investigator}</p>
</ac:rich-text-body></ac:structured-macro>

<h2>Investigation Summary</h2>
<table>
<tbody>
<tr><th>Ticket</th><td>${ticket ? `#${ticket.id} — ${escapeHtml(ticket.subject)}` : 'No ticket'}</td></tr>
<tr><th>Organization</th><td>${ticket?.orgName ? escapeHtml(ticket.orgName) : 'N/A'}</td></tr>
<tr><th>Customer Timezone</th><td>${escapeHtml(customerTimezone)}</td></tr>
<tr><th>Root Cause</th><td>${escapeHtml(diagnosis.rootCause)}</td></tr>
<tr><th>Root Cause Tags</th><td>${rootCauseTags.map(t => `<ac:structured-macro ac:name="status"><ac:parameter ac:name="colour">Blue</ac:parameter><ac:parameter ac:name="title">${t}</ac:parameter></ac:structured-macro>`).join(' ')}</td></tr>
<tr><th>Log Sources</th><td>${escapeHtml(logSources)}</td></tr>
<tr><th>Resolved</th><td>${now}</td></tr>
</tbody>
</table>

<h2>AI Diagnosis Summary</h2>
<p>${escapeHtml(diagnosis.summary)}</p>

<h2>Key Evidence</h2>
<ul>
${correlatedEvidence || '<li>No correlated logs identified</li>'}
</ul>

${diagnosis.appliedTroubleshooting ? `<h2>Troubleshooting Steps</h2>\n<p>${escapeHtml(diagnosis.appliedTroubleshooting)}</p>` : ''}

<h2>Closure Note</h2>
<ac:structured-macro ac:name="code"><ac:parameter ac:name="language">text</ac:parameter><ac:plain-text-body><![CDATA[${internalNote}]]></ac:plain-text-body></ac:structured-macro>

${diagnosis.logSuggestions.length > 0 ? `<h2>Additional Log Sources Suggested</h2>\n<ul>${diagnosis.logSuggestions.map(s => `<li><strong>${escapeHtml(s.source)}:</strong> ${escapeHtml(s.reason)}</li>`).join('\n')}</ul>` : ''}
`.trim();
}

/**
 * Derive root cause category tags from the AI's root cause text.
 */
function extractRootCauseTags(rootCause: string): string[] {
  const lower = rootCause.toLowerCase();
  const tags: string[] = [];
  if (lower.includes('ccs') || lower.includes('call control')) tags.push('noc:root-ccs');
  if (lower.includes('sip') || lower.includes('invite') || lower.includes('routing')) tags.push('noc:root-sip');
  if (lower.includes('pbx') || lower.includes('extension') || lower.includes('registration')) tags.push('noc:root-pbx');
  if (lower.includes('network') || lower.includes('connectivity') || lower.includes('latency')) tags.push('noc:root-network');
  if (lower.includes('audio') || lower.includes('media') || lower.includes('rtp')) tags.push('noc:root-media');
  if (lower.includes('fdx') || lower.includes('websocket')) tags.push('noc:root-fdx');
  if (lower.includes('config') || lower.includes('provision') || lower.includes('setting')) tags.push('noc:root-config');
  if (lower.includes('carrier') || lower.includes('trunk') || lower.includes('upstream')) tags.push('noc:root-carrier');
  if (lower.includes('station') || lower.includes('workstation') || lower.includes('hardware')) tags.push('noc:root-workstation');
  if (tags.length === 0) tags.push('noc:root-unknown');
  return tags;
}

function escapeHtml(text: string): string {
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

/**
 * Save a completed investigation as a Confluence child page.
 */
export async function saveInvestigationToConfluence(
  settings: AiSettings,
  ticket: ZendeskTicket | null,
  diagnosis: DiagnosisResult,
  internalNote: string,
  customerTimezone: string,
): Promise<SavedInvestigation> {
  if (!hasConfluenceCredentials(settings)) {
    throw new Error('Confluence credentials not configured. Add Jira/Atlassian email + token in AI Settings.');
  }

  const investigator = settings.jiraEmail?.split('@')[0] ?? 'NocLense';
  const dateStr = new Date().toISOString().slice(0, 10);
  const ticketRef = ticket ? `#${ticket.id}` : 'no-ticket';
  const shortCause = diagnosis.rootCause.slice(0, 50).replace(/[^a-zA-Z0-9 -]/g, '');
  const title = `${dateStr} ${ticketRef} — ${shortCause}`;

  const body = buildInvestigationPageBody(ticket, diagnosis, internalNote, customerTimezone, investigator);

  const base = confluenceBase(settings);
  const url = `${base}/wiki/api/v2/pages`;

  const payload = {
    spaceId: settings.confluenceSpaceId,
    parentId: settings.confluenceParentPageId,
    status: 'current',
    title,
    body: {
      representation: 'storage',
      value: body,
    },
  };

  const res = await fetch(url, {
    method: 'POST',
    headers: confluenceHeaders(settings),
    body: JSON.stringify(payload),
  });

  if (!res.ok) {
    const text = await res.text().catch(() => res.statusText);
    throw new Error(`Confluence save failed (${res.status}): ${text.slice(0, 300)}`);
  }

  const data = await res.json();
  const pageUrl = data._links?.base
    ? `${data._links.base}${data._links.webui}`
    : `https://${settings.jiraSubdomain}/wiki${data._links?.webui ?? ''}`;

  return {
    pageId: String(data.id),
    title: data.title,
    url: pageUrl,
  };
}

/**
 * Search past investigations in Confluence using CQL.
 */
export async function searchConfluenceInvestigations(
  settings: AiSettings,
  keywords: string[],
  limit: number = 5,
): Promise<ConfluenceSearchResult[]> {
  if (!hasConfluenceCredentials(settings)) return [];

  const cleaned = keywords.map(k => k.trim().replace(/['"]/g, '')).filter(k => k.length > 2);
  if (cleaned.length === 0) return [];

  const textQuery = cleaned.map(k => `"${k}"`).join(' OR ');
  const cql = `ancestor = ${settings.confluenceParentPageId} AND type = page AND (text ~ ${textQuery}) ORDER BY lastmodified DESC`;

  const base = confluenceBase(settings);
  const url = `${base}/wiki/rest/api/content/search?cql=${encodeURIComponent(cql)}&limit=${limit}&expand=metadata.labels`;

  try {
    const res = await fetch(url, { headers: confluenceHeaders(settings) });
    if (!res.ok) {
      console.warn(`[Confluence Search] ${res.status} — ${await res.text().catch(() => '')}`);
      return [];
    }

    const data = await res.json();
    return (data.results ?? []).map((r: Record<string, unknown>) => {
      const links = r._links as Record<string, string> | undefined;
      return {
        pageId: String(r.id),
        title: (r.title as string) ?? '',
        excerpt: ((r.excerpt as string) ?? '').replace(/<[^>]+>/g, '').slice(0, 200),
        url: links?.base ? `${links.base}${links.webui}` : '',
        lastModified: ((r as Record<string, unknown>).history as Record<string, unknown>)?.lastUpdated as string ?? '',
      };
    });
  } catch (e) {
    console.warn('[Confluence Search] Failed:', e);
    return [];
  }
}
