export const TIMEZONE_OPTIONS: { label: string; value: string }[] = [
  { label: 'UTC', value: 'UTC' },
  { label: 'Eastern (US & Canada)', value: 'Eastern Time (US & Canada)' },
  { label: 'Central (US & Canada)', value: 'Central Time (US & Canada)' },
  { label: 'Mountain (US & Canada)', value: 'Mountain Time (US & Canada)' },
  { label: 'Pacific (US & Canada)', value: 'Pacific Time (US & Canada)' },
  { label: 'Arizona (no DST)', value: 'Arizona' },
  { label: 'Alaska', value: 'Alaska' },
  { label: 'Hawaii', value: 'Hawaii' },
  { label: 'Atlantic (Canada)', value: 'Atlantic Time (Canada)' },
  { label: 'Newfoundland', value: 'Newfoundland' },
  { label: 'London (UK)', value: 'London' },
  { label: 'Paris / Berlin / CET', value: 'Central European Time' },
  { label: 'Moscow', value: 'Moscow' },
  { label: 'Dubai', value: 'Abu Dhabi' },
  { label: 'India (IST)', value: 'Mumbai' },
  { label: 'Singapore / HK', value: 'Singapore' },
  { label: 'Tokyo / Japan', value: 'Tokyo' },
  { label: 'Sydney (AEDT)', value: 'Sydney' },
  { label: 'Melbourne', value: 'Melbourne' },
  { label: 'Perth (AWST)', value: 'Perth' },
  { label: 'Auckland', value: 'Auckland' },
];
